name: Tests

on:
  push:
    branches:
      - trunk
  pull_request:

permissions:
  contents: read

jobs:
  php:
    name: PHP ${{ matrix.php }}
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        php: [ '7.4', '8.0', '8.1', '8.2', '8.3', '8.4' ]
    steps:
      - uses: actions/checkout@v5
        with:
          persist-credentials: false

      - uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ matrix.php }}
          coverage: none
          tools: composer

      - uses: ramsey/composer-install@v3
        with:
          composer-options: ${{ matrix.php != '7.4' && '--ignore-platform-reqs' || '' }}

      - run: composer run-script test:unit

  javascript:
    name: JavaScript
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5
        with:
          persist-credentials: false

      - uses: actions/setup-node@v6
        with:
          node-version-file: .nvmrc
          cache: npm

      - run: npm ci

      - run: npm run test:unit

  integration:
    name: WordPress integration
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5
        with:
          persist-credentials: false

      - uses: actions/setup-node@v6
        with:
          node-version-file: .nvmrc
          cache: npm

      - uses: shivammathur/setup-php@v2
        with:
          php-version: '7.4'
          coverage: none
          tools: composer

      - uses: ramsey/composer-install@v3

      - run: npm ci

      - run: npm run build

      - run: npx wp-env start

      - run: npm run test:php-integration
